### PR TITLE
ws2811.c: fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with gcc 4.8 (which has been added by commit 391f6e856d28510bd9ae4efd3a166da7f73613ab):

```
lib/ws2811.c: In function 'ws2811_set_custom_gamma_factor':
lib/ws2811.c:1289:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int chan = 0; chan < RPI_PWM_CHANNELS; chan++)
     ^
lib/ws2811.c:1289:5: note: use option -std=c99 or -std=gnu99 to compile your code
lib/ws2811.c:1295:11: error: 'for' loop initial declarations are only allowed in C99 mode
           for(int counter = 0; counter < 256; counter++)
           ^
```

Fixes:
 - http://autobuild.buildroot.org/results/3d037922484bfc45d0f985f87b38f20c5a4ab064

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by Gadgetoid** [comment]
I guess this is *technically* a regression since there's no need for that commit to break back compat... but... GCC 4.8. I won't ask.

Thank you!

(This repository could use some continuous integration)
